version: "3.8"

services:
  postgres:
    image: postgres:18
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: spring_store        
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql

  spring-app:
    build: ./Backend
    container_name: spring_blog_app
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/spring_store
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 1234
  
  frontend:
    build: ./Frontend
    container_name: frontend_app
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_URL: http://spring-app:8080
    depends_on:
      - spring-app
volumes:
  pg_data:
